name: SkinsRestorer
main: skinsrestorer.bukkit.SkinsRestorer
load: STARTUP
version: 12.9.4
authors: [Blackfire62, Th3Tr0LLeR]
commands:
  skinsrestorer:
    aliases: [sr]
    description: Admin commands.
  skin:
    description: Sets your skin.
  clearskin:
    description: Removes your skin.
  skins:
    description: Opens the skins menu.